<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Error Handling</title>
  </head>
  <body>
    <script>
      class MathUtil {
        static sum(...numbers) {
          if (numbers.length === 0) {
            throw new Error("Total parameter harus lebih dari 0");
          }

          let total = 0;
          for (const number of numbers) {
            total += number;
          }
          return total;
        }
      }
      //   di atas kita masih menggunakan class yang sama seperti di file Error

      //   di bawah ini kita belajar mengenai try and catch and finally,
      try {
        console.info(MathUtil.sum()); //kode pertama di block try ini akan di eksekusi jika terjadi error
        console.info("Eko"); //yang kedua tidak akan di eksekusi
      } catch (error) {
        console.info(`Terjadi error : ${error.message}`); //jika ada eeror akan langsung di tangkap di block catch
        // bagian error.massage (massage merupakan property yang ada di error, bagian param catch merupakan error yang di mksd di try)
        // yang mana menampilkan Throw new error di class di atas
      } finally {
        console.info("Program selesai");
        // nah finaly ada kode yang akan terus di tampilkan mau error atau pun tidak
      }

      console.info("Khannedy");

      class Counter {
        #counter = 1;

        next() {
          try {
            return this.#counter; //kita bisa menggunakan try dan finaly tanpa catch, bisa liat aja video tutorial nya
          } finally {
            this.#counter++;
          }
        }
      }

      const counter = new Counter();
      console.info(counter.next());
      console.info(counter.next());
      console.info(counter.next());
      console.info(counter.next());
      console.info(counter.next());
      //   kita pangiil class nya
    </script>
  </body>
</html>
